---
webhook_url: 'https://discord.com/api/webhooks/902566530896760855/YvMwTdzNIbv64kwQfeciJHMqDhTF9j2fe1ELfchdlgUtoNar_wFbnwK5zV_pzi1_deNF'
#webhook_url: 'https://discord.com/api/webhooks/838804816515301418/7aUdJPR7SpUDqxKCDnB0_-NvPRfUvK0HGnenmpyo9ls6JUDi3fbnkyLrlk_jIXIMVZPf'
users: ['nikemallofindia','nikepacific','onlydrops.in','kitco_official']
